import artwork from './artwork.js'
import article from './article.js'
import author from './author.js'
import category from './category.js'
import city from './city.js'
import country from './country.js'
import creator from './creator.js'
import finish from './finish.js'
import location from './location.js'
import material from './material.js'
import materialType from './materialType.js'
import medium from './medium.js'
import photographer from './photographer.js'
import webflowSyncSettings from './webflowSyncSettings.js'

export const schemaTypes = [artwork, article, author, category, city, country, creator, finish, location, material, materialType, medium, photographer, webflowSyncSettings] 